In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 2. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**2.1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [2]:
(np.ones(20) * 2 ** np.arange(1, 21)) / np.arange(1, 21)

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [3]:
np.sum(0.1**(3*np.arange(0, 6)) * 0.2**(4*np.arange(0, 6)))

1.00000160000256

**2.3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [4]:
zeros_matr = np.zeros((8,8))
zeros_matr[1::2, 1::2] = 1
zeros_matr[0::2, 0::2] = 1
zeros_matr

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

**2.4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [5]:
def to_polar(coords):
    
    r = np.linalg.norm(coords)
    phi = np.arccos(coords[0]/r)
    
    return r, phi

In [6]:
X = np.random.random((5, 2))
X_polar = np.apply_along_axis(to_polar, axis=1, arr=X)

print('Декартовы координаты:\n', X)
print('Полярные координаты:\n', X_polar)

Декартовы координаты:
 [[0.81765718 0.60165672]
 [0.90231047 0.43948543]
 [0.58857877 0.11125212]
 [0.72024005 0.84737245]
 [0.29171914 0.0055893 ]]
Полярные координаты:
 [[1.01516209 0.63437049]
 [1.00364916 0.45324758]
 [0.59900084 0.18681422]
 [1.11210871 0.86632044]
 [0.29177268 0.01915751]]


**2.5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [7]:
X = np.random.random((10, 10))

print(np.argmax(X) // 10, np.argmax(X) % 10)

1 2


In [8]:
# Проверка
np.where(X == X.max())

(array([1]), array([2]))

**2.6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [9]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))

distances = np.apply_along_axis(np.linalg.norm, axis=1, arr=X - y)
X[distances.argmin()]

array([0.63642629, 0.81821785])

**2.7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [10]:
def func(x):
    
    if x < 0:
        return x**2 + 2*x + 6
    elif 0 <= x <= 2:
        return x + 6
    else:
        return x**2 + 4*x - 4

In [11]:
v_func = np.vectorize(func)
v_func(np.arange(-3, 4))

array([ 9,  6,  5,  6,  7,  8, 17])

**2.8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [12]:
X = np.random.random((10, 10))

(X - np.expand_dims(X.mean(axis=1), axis=1))

array([[ 0.11775197, -0.11238433,  0.27648672, -0.31370482, -0.08571367,
        -0.34020748, -0.16902181,  0.46031537,  0.0146959 ,  0.15178214],
       [ 0.49141582, -0.36175556,  0.05439405,  0.24278346, -0.27478257,
        -0.42846824, -0.04480587,  0.47356916, -0.40822249,  0.25587224],
       [ 0.17309577,  0.34017696, -0.3338262 , -0.32365003, -0.46610478,
        -0.05267019,  0.34081334,  0.20945236,  0.07186144,  0.04085133],
       [ 0.34059743, -0.24600171,  0.21562649, -0.21041089,  0.0982959 ,
        -0.33814497, -0.37275025,  0.38139029, -0.22408438,  0.35548209],
       [ 0.39273851,  0.01897577,  0.01113225, -0.45912638, -0.14786006,
        -0.00702618,  0.39562231, -0.21712376,  0.28695782, -0.27429026],
       [ 0.00059095, -0.11408575, -0.45215518, -0.17787941,  0.23685336,
         0.15617598,  0.24666325,  0.14704368,  0.10045047, -0.14365736],
       [ 0.01821371,  0.29132006, -0.53101118, -0.41253873,  0.23094143,
        -0.13999222, -0.08053296,  0.38112068

In [13]:
# Проверка
(X - np.expand_dims(X.mean(axis=1), axis=1)).mean(axis=1)

array([ 4.44089210e-17, -3.33066907e-17,  7.77156117e-17, -1.11022302e-17,
       -2.22044605e-17, -4.44089210e-17,  1.11022302e-16,  0.00000000e+00,
        1.11022302e-17,  1.11022302e-17])

**2.9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [14]:
X = np.random.normal(loc=5, scale=2., size=1000)
print('Среднее:', X.mean(), 'Дисперсия:', X.var())

Среднее: 4.9033738940127645 Дисперсия: 4.025533121148183


**2.10.** Создать матрицу (NB. БЕЗ ЦИКЛОВ И ИЗМЕНЕНИЯ ОТДЕЛЬНЫХ ЭЛЕМЕНТОВ):

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [15]:
X = np.array([[0, 1, 2, 3, 4]]) 

In [16]:
np.array(list(map(lambda shift: np.roll(X, -shift), np.arange(5))))[:, 0, :]

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0],
       [2, 3, 4, 0, 1],
       [3, 4, 0, 1, 2],
       [4, 0, 1, 2, 3]])

In [17]:
np.arange(5)

array([0, 1, 2, 3, 4])

**2.11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [18]:
np.random.seed(42)

In [19]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()

        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
print(sample([50, 3, 1, 7, 20], 5))
print(sample([50, 3, 1, 7, 20], 5))
print(sample([50, 3, 1, 7, 20], 5))
print(sample([50, 3, 1, 7, 20], 5))
print(sample([50, 3, 1, 7, 20], 5))
print(sample([50, 3, 1, 7, 20], 5))
print(sample([50, 3, 1, 7, 20], 5))

[0, 4, 3, 0, 0]
[0, 0, 4, 0, 3]
[0, 4, 4, 0, 0]
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]
[4, 0, 0, 0, 0]
[0, 0, 0, 4, 4]


Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [20]:
np.random.seed(42)

In [21]:
def get_one_sample(x, val):

    cumsum = np.cumsum(x)
    filtered = np.where(cumsum <= val, 1, 0)
    idx = np.where(filtered==0)[0][0]    
    
    return idx          

In [22]:
def sample_numpy(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    vals = list(map(lambda _: s * np.random.random(), np.arange(5)))
    res = list(map(lambda val: get_one_sample(x, val), vals))
              
    return res 

print(sample_numpy([50, 3, 1, 7, 20], 5))
print(sample_numpy([50, 3, 1, 7, 20], 5))
print(sample_numpy([50, 3, 1, 7, 20], 5))
print(sample_numpy([50, 3, 1, 7, 20], 5))
print(sample_numpy([50, 3, 1, 7, 20], 5))
print(sample_numpy([50, 3, 1, 7, 20], 5))
print(sample_numpy([50, 3, 1, 7, 20], 5))  

[0, 4, 3, 0, 0]
[0, 0, 4, 0, 3]
[0, 4, 4, 0, 0]
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]
[4, 0, 0, 0, 0]
[0, 0, 0, 4, 4]
