In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 2. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**2.1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [2]:
(np.ones(20) * 2 ** np.arange(1, 21)) / np.arange(1, 21)

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [3]:
np.sum(0.1**(3*np.arange(0, 6)) * 0.2**(4*np.arange(0, 6)))

1.00000160000256

**2.3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [4]:
zeros_matr = np.zeros((8,8))
zeros_matr[1::2, 1::2] = 1
zeros_matr[0::2, 0::2] = 1
zeros_matr

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

**2.4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [6]:
def to_polar(coords):
    
    r = np.linalg.norm(coords)
    phi = np.arccos(coords[0]/r)
    
    return r, phi

In [7]:
X = np.random.random((5, 2))
X_polar = np.apply_along_axis(to_polar, axis=1, arr=X)

print('Декартовы координаты:\n', X)
print('Полярные координаты:\n', X_polar)

Декартовы координаты:
 [[0.79726683 0.63658348]
 [0.95204999 0.03883057]
 [0.93582119 0.13885226]
 [0.80813949 0.51701254]
 [0.57197659 0.93639241]]
Полярные координаты:
 [[1.0202318  0.67379953]
 [0.95284154 0.04076367]
 [0.9460662  0.14730011]
 [0.95937032 0.56914046]
 [1.09726386 1.02245162]]


**2.5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [8]:
X = np.random.random((10, 10))

print(np.argmax(X) // 10, np.argmax(X) % 10)

1 8


In [9]:
# Проверка
np.where(X == X.max())

(array([1]), array([8]))

**2.6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [10]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))

distances = np.apply_along_axis(np.linalg.norm, axis=1, arr=X - y)
X[distances.argmin()]

array([0.66919911, 0.05890638])

**2.7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [11]:
def func(x):
    
    if x < 0:
        return x**2 + 2*x + 6
    elif 0 <= x <= 2:
        return x + 6
    else:
        return x**2 + 4*x - 4

In [12]:
v_func = np.vectorize(func)
v_func(np.arange(-3, 4))

array([ 9,  6,  5,  6,  7,  8, 17])

**2.8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [13]:
X = np.random.random((10, 10))

(X - np.expand_dims(X.mean(axis=1), axis=1))

array([[-0.19762029, -0.4269559 , -0.35361143,  0.01303827,  0.33240572,
         0.34957416, -0.08261689,  0.35387067, -0.36939671,  0.38131239],
       [ 0.18636949, -0.18984479,  0.13955525,  0.17866217,  0.13907942,
         0.05252254, -0.26619333, -0.21550682,  0.1868714 , -0.21151535],
       [-0.08555149,  0.23312659,  0.28960585, -0.52511492,  0.21663687,
         0.25714068,  0.14519483, -0.42193502,  0.14179984, -0.25090322],
       [-0.26479083,  0.01406154,  0.43502616, -0.34402583,  0.33981944,
        -0.40971349,  0.30715212, -0.11504283,  0.45276433, -0.41525062],
       [ 0.01943348, -0.23462905,  0.39566097, -0.02948747, -0.17642213,
        -0.25739902, -0.08795978, -0.331098  ,  0.42324667,  0.27865433],
       [-0.2303882 , -0.24404511, -0.23211768,  0.36128695, -0.2095216 ,
        -0.23153396,  0.45940202,  0.20653451,  0.39349627, -0.27311318],
       [ 0.17785815, -0.23306108, -0.07210699,  0.03123024,  0.17824688,
        -0.32082574, -0.4682076 ,  0.02470472

In [14]:
# Проверка
(X - np.expand_dims(X.mean(axis=1), axis=1)).mean(axis=1)

array([-1.11022302e-17,  1.11022302e-16, -3.33066907e-17,  1.11022302e-17,
        3.33066907e-17, -2.22044605e-17, -6.66133815e-17,  1.55431223e-16,
       -3.33066907e-17,  1.11022302e-17])

**2.9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [15]:
X = np.random.normal(loc=5, scale=2., size=1000)
print('Среднее:', X.mean(), 'Дисперсия:', X.var())

Среднее: 4.971739892959535 Дисперсия: 4.148248456051955


**2.10.** Создать матрицу (NB. БЕЗ ЦИКЛОВ И ИЗМЕНЕНИЯ ОТДЕЛЬНЫХ ЭЛЕМЕНТОВ):

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [16]:
X = np.array([[0, 1, 2, 3, 4]]) 

In [17]:
np.array(list(map(lambda shift: np.roll(X, -shift), np.arange(5))))[:, 0, :]

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0],
       [2, 3, 4, 0, 1],
       [3, 4, 0, 1, 2],
       [4, 0, 1, 2, 3]])

In [18]:
np.arange(5)

array([0, 1, 2, 3, 4])

**2.11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [149]:
np.random.seed(42)

In [150]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()

        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
print(sample([50, 3, 1, 7, 20], 5))
print(sample([50, 3, 1, 7, 20], 5))
print(sample([50, 3, 1, 7, 20], 5))
print(sample([50, 3, 1, 7, 20], 5))
print(sample([50, 3, 1, 7, 20], 5))
print(sample([50, 3, 1, 7, 20], 5))
print(sample([50, 3, 1, 7, 20], 5))

[0, 4, 3, 0, 0]
[0, 0, 4, 0, 3]
[0, 4, 4, 0, 0]
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]
[4, 0, 0, 0, 0]
[0, 0, 0, 4, 4]


Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [151]:
np.random.seed(42)

In [152]:
def get_one_sample(x, val):

    cumsum = np.cumsum(x)
    filtered = np.where(cumsum <= val, 1, 0)
    idx = np.where(filtered==0)[0][0]    
    
    return idx          

In [153]:
def sample_numpy(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    vals = list(map(lambda _: s * np.random.random(), np.arange(5)))
    res = list(map(lambda val: get_one_sample(x, val), vals))
              
    return res 

print(sample_numpy([50, 3, 1, 7, 20], 5))
print(sample_numpy([50, 3, 1, 7, 20], 5))
print(sample_numpy([50, 3, 1, 7, 20], 5))
print(sample_numpy([50, 3, 1, 7, 20], 5))
print(sample_numpy([50, 3, 1, 7, 20], 5))
print(sample_numpy([50, 3, 1, 7, 20], 5))
print(sample_numpy([50, 3, 1, 7, 20], 5))  

[0, 4, 3, 0, 0]
[0, 0, 4, 0, 3]
[0, 4, 4, 0, 0]
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]
[4, 0, 0, 0, 0]
[0, 0, 0, 4, 4]
